# Generated by Django 5.0.6 on 2024-10-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklama', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Catagory', 'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Catagory',
        ),
    ]
