# Generated by Django 5.0.6 on 2024-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklama', '0004_alter_product_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='surat',
            field=models.FileField(default=None, upload_to='product_image'),
        ),
    ]
