# Generated by Django 5.0.6 on 2024-10-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklama', '0005_alter_product_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
